# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thinking Non-Linearly
name: Thinking Non-Linearly
email: zerbethea@gmail.com
permalink: /:year/:month/:day/:title/
description: "'The inner machanations of my mind are an enigma.' - Patrick Star"
baseurl: "" # the subpath of your site, e.g. /blog
url: "tzerbe.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  tzerbe

# Build settings
markdown: kramdown
